### ISSUE TITLE
plusminus34 home row issues on layer _left

### ISSUE THREAD

**Issue by tuptusstokrotka** [tuptusstokrotka/MechanicalKeyboard#1]
home row buttons as a multi action keys (hold/press) works fine,
but keys on row 1 should  output from  '!' (SHIFT +1) to the ')' (SHIFT +0).

however the result is just a number key, thus SHIFT modifiers are ignored in that cases

**Comment by tuptusstokrotka** [comment]
when using mod-tap/tapdance there are 2 problems to face.
1. Modifier accepts only basic keycodes, and ! is not basic. 
2. Modifier will not trigger process_record_user thus it's not possible to use e.g. F15 and then output required keycode.

**Comment by tuptusstokrotka** [comment]
1. Modifier accepts only basic keycodes and ! is not basic.
2. Modifiers will not trigger the process_record_user thus it's not possible to use e.g. F15 and then execute required key combination

**Comment by julian-tarczynski** [comment]
1. Modifier accepts only basic keycodes and ! is not basic.
2. Modifiers will not trigger the process_record_user thus it's not possible to use e.g. F15 and then execute required key combination

solution is to use space cadet configured to match the expected result
